apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devapp.fullname" . }}-app-config
  labels:
  {{- include "devapp.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.appConfig.springDatasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.appConfig.springDatasourceUsername | quote
    }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: {{ .Values.appConfig.springJpaPropertiesHibernateDialect
    | quote }}